import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SmoothScroll from "@/components/SmoothScroll";
import TopbarBanner from "@/components/TopbarBanner";

const CabinetGrotesk = localFont({
  src: "../../public/Fonts/CabinetGrotesk.otf",
});

export const metadata: Metadata = {
  title: "Karma UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${CabinetGrotesk.className} bg-background`}>
        <SmoothScroll>
          <div className="sticky top-0">
            <TopbarBanner />
            <Navbar />
          </div>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
